export const endpoints = {
    auth: {
        login: "/auth/login",
        me: "/auth/me",
        completeSignup: "/auth/complete-signup",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password"
    },
    dashboard: "/reports/dashboard",
    staff: "/staff",
    staffSummary: "/staff/summary",
    departments: "/departments",
    departmentStatus: (id: string) => `/departments/${id}/status`,
    adminPlatformFee: "/admin/platform-fee",
    members: "/members",
    member: (id: string) => `/members/${id}`,
    memberStatus: (id: string) => `/members/${id}/status`,
    memberSelfProfile: "/members/me/profile",
    roles: "/roles",
    assignRole: "/roles/assign",
    policies: "/policies",
    policy: (id: string) => `/policies/${id}`,
    policyDeactivate: (id: string) => `/policies/${id}/deactivate`,
    events: "/events",
    eventPreview: "/events/preview",
    eventDetail: (id: string) => `/events/${id}`,
    eventFinancialSummary: (id: string) => `/events/${id}/finance`,
    eventDelete: (id: string) => `/events/${id}`,
    eventClose: (id: string) => `/events/${id}/close`,
    eventContributions: (id: string) => `/events/${id}/contributions`,
    contributions: "/contributions",
    contributionPay: "/contributions/pay",
    contributionWaive: (id: string) => `/contributions/${id}/waive`,
    contributionPaymentLatest: "/contribution-payments/latest",
    contributionPaymentOrderStatus: (id: string) => `/contribution-payments/orders/${id}/status`,
    reports: {
        eventSummary: "/reports/event-summary",
        memberHistory: "/reports/member-history",
        outstanding: "/reports/outstanding",
        departmentParticipation: "/reports/department-participation",
        yearlySummary: "/reports/yearly-summary",
        exportPdf: "/reports/export/pdf"
    },
    notifications: "/notifications/activity",
    auditLogs: "/audit-logs",
    auditLogSummary: "/audit-logs/summary"
} as const;
